title: Container to Cloud
description: Workshop documentation to build a local container image and deploy it ti IBM Code Engine
plugins:
  - jekyll-remote-theme
remote_theme: pages-themes/hacker@v0.2.0
markdown: kramdown
highlighter: rouge

exclude:
  - LICENSE
  - .vscode/
  - .venv
  - .gitignore
