# Red Hat's Python minimal base image
FROM registry.access.redhat.com/ubi9/python-312-minimal

# Set the working directory in the container
WORKDIR /app

# Set a non-privileged user
USER 1001

# Copy the requirements file
COPY requirements.txt .

# Install the dependencies
RUN pip3 install --no-cache-dir -r requirements.txt

# Copy the application code
COPY app.py .

# Set the default port to 8000
ENV PORT=8000

# Expose the port
EXPOSE $PORT

# Run the command to start the development server
CMD ["sh", "-c", "uvicorn app:app --host 0.0.0.0 --port ${PORT}"]
